// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRAc1MnwrUsqEF-ZEJIZzi9x2NouR6TKY',
    appId: '1:901662729445:android:8c1e7af3197720427e600c',
    messagingSenderId: '901662729445',
    projectId: 'testlogin-85595',
    databaseURL: 'https://testlogin-85595-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-85595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSnm_u0HSjB5mQzWPd_OgU1vNV0K0FG2Q',
    appId: '1:901662729445:ios:b1bf697b4b561e177e600c',
    messagingSenderId: '901662729445',
    projectId: 'testlogin-85595',
    databaseURL: 'https://testlogin-85595-default-rtdb.firebaseio.com',
    storageBucket: 'testlogin-85595.appspot.com',
    androidClientId: '901662729445-d5hfebv52hk3on2g91fqoqmofll0mh1t.apps.googleusercontent.com',
    iosClientId: '901662729445-40j87s0fdr7nn1vbr38lh4jirbqhl5sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPracticeMission',
  );
}
